export default{
  otaData: [
    {
      reviewPlatform:TripAdvisor,
      data:[
        {
          hotelName:'Galaxy',
          reviews:'5',
          positiveReviews:'52',
          neutralReviews:'28',
          negativeReviews:'20'
        },
        {
          hotelName:'Star',
          reviews:'28',
          positiveReviews:'26',
          neutralReviews:'4',
          negativeReviews:'70'
        },
        {
          hotelName:'Moon',
          reviews:'55',
          positiveReviews:'82',
          neutralReviews:'14',
          negativeReviews:'4'
        }
      ]
    },
    {
      reviewPlatform:Booking,
      data:[
        {
          hotelName:'Galaxy',
          reviews:'5',
          positiveReviews:'52',
          neutralReviews:'28',
          negativeReviews:'20'
        },
        {
          hotelName:'Star',
          reviews:'28',
          positiveReviews:'26',
          neutralReviews:'4',
          negativeReviews:'70'
        },
        {
          hotelName:'Moon',
          reviews:'55',
          positiveReviews:'82',
          neutralReviews:'14',
          negativeReviews:'4'
        }
      ]
    },
    {
      reviewPlatform:Agoda,
      data:[
        {
          hotelName:'Galaxy',
          reviews:'5',
          positiveReviews:'52',
          neutralReviews:'28',
          negativeReviews:'20'
        },
        {
          hotelName:'Star',
          reviews:'28',
          positiveReviews:'26',
          neutralReviews:'4',
          negativeReviews:'70'
        },
        {
          hotelName:'Moon',
          reviews:'55',
          positiveReviews:'82',
          neutralReviews:'14',
          negativeReviews:'4'
        }
      ]
    },
    {
      reviewPlatform:MakeMyTrip,
      data:[
        {
          hotelName:'Galaxy',
          reviews:'5',
          positiveReviews:'52',
          neutralReviews:'28',
          negativeReviews:'20'
        },
        {
          hotelName:'Star',
          reviews:'28',
          positiveReviews:'26',
          neutralReviews:'4',
          negativeReviews:'70'
        },
        {
          hotelName:'Moon',
          reviews:'55',
          positiveReviews:'82',
          neutralReviews:'14',
          negativeReviews:'4'
        }
      ]
    },
    {
      reviewPlatform:Expedia,
      data:[
        {
          hotelName:'Galaxy',
          reviews:'5',
          positiveReviews:'52',
          neutralReviews:'28',
          negativeReviews:'20'
        },
        {
          hotelName:'Star',
          reviews:'28',
          positiveReviews:'26',
          neutralReviews:'4',
          negativeReviews:'70'
        },
        {
          hotelName:'Moon',
          reviews:'55',
          positiveReviews:'82',
          neutralReviews:'14',
          negativeReviews:'4'
        }
      ]
    },
    {
      reviewPlatform:Goibibo,
      data:[
        {
          hotelName:'Galaxy',
          reviews:'5',
          positiveReviews:'52',
          neutralReviews:'28',
          negativeReviews:'20'
        },
        {
          hotelName:'Star',
          reviews:'28',
          positiveReviews:'26',
          neutralReviews:'4',
          negativeReviews:'70'
        },
        {
          hotelName:'Moon',
          reviews:'55',
          positiveReviews:'82',
          neutralReviews:'14',
          negativeReviews:'4'
        }
      ]
    }
  ]
}